import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import NavbarDashboard from "../Components/NavbarDashboard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600', '700'], // Poppins requires specific weights if it's not a variable font
  variable: '--font-poppins', // Optional: for use with Tailwind or CSS variables
});


export const metadata: Metadata = {
  title: "Arboriza itaboraí",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="pt-br" className={`${geistSans.variable} ${geistMono.variable} ${poppins.className}`} data-scroll-behavior="target">
        <NavbarDashboard/>
        {children}
    </div>
  );
}
